/*
@TargetNode='andreascloud.cloudapp.net'
@GeneratedBy=andreas.storlien
@GenerationDate=10/29/2014 10:44:59
@GenerationHost=ANDREAS
*/

instance of MSFT_RoleResource as $MSFT_RoleResource1ref
{
ResourceID = "[WindowsFeature]IIS";
 Ensure = "Present";
 SourceInfo = "C:\\Program Files\\WindowsPowerShell\\DSC\\TestWebSite\\TestWebSite.ps1::8::9::WindowsFeature";
 Name = "Web-Server";
 ModuleName = "PSDesiredStateConfiguration";
 ModuleVersion = "1.0";


};
instance of MSFT_RoleResource as $MSFT_RoleResource2ref
{
ResourceID = "[WindowsFeature]ASP";
 Ensure = "Present";
 SourceInfo = "C:\\Program Files\\WindowsPowerShell\\DSC\\TestWebSite\\TestWebSite.ps1::14::9::WindowsFeature";
 Name = "Web-Asp-Net45";
 ModuleName = "PSDesiredStateConfiguration";
 ModuleVersion = "1.0";


};
instance of OMI_ConfigurationDocument
{
 Version="1.0.0";
 Author="andreas.storlien";
 GenerationDate="10/29/2014 10:44:59";
 GenerationHost="ANDREAS";
};
