/*
@TargetNode='andreascloud.cloudapp.net'
@GeneratedBy=andreas.storlien
@GenerationDate=10/29/2014 14:01:36
@GenerationHost=ANDREAS
*/

instance of MSFT_RoleResource as $MSFT_RoleResource1ref
{
ResourceID = "[WindowsFeature]DSCServiceFeature";
 Ensure = "Present";
 SourceInfo = "C:\\Program Files\\WindowsPowerShell\\DSC\\NewPullServer\\NewPullServer.ps1::12::9::WindowsFeature";
 Name = "DSC-Service";
 ModuleName = "PSDesiredStateConfiguration";
 ModuleVersion = "1.0";


};
instance of MSFT_xDSCWebService as $MSFT_xDSCWebService1ref
{
ResourceID = "[xDSCWebService]PSDSCPullServer";
 PhysicalPath = "C:\\inetpub\\wwwroot\\PSDSCPullServer";
 State = "Started";
 CertificateThumbPrint = "0B8D21D9A61EE3B5737CD7CF9ECC2E19C4661A7A";
 Ensure = "Present";
 ConfigurationPath = "C:\\Program Files\\WindowsPowerShell\\DscService\\Configuration";
 SourceInfo = "C:\\Program Files\\WindowsPowerShell\\DSC\\NewPullServer\\NewPullServer.ps1::18::9::xDscWebService";
 EndpointName = "PSDSCPullServer";
 ModuleName = "xPSDesiredStateConfiguration";
 Port = 8080;
 ModulePath = "C:\\Program Files\\WindowsPowerShell\\DscService\\Modules";
 ModuleVersion = "3.0.2.0";

DependsOn = {

    "[WindowsFeature]DSCServiceFeature"};


};
instance of MSFT_xDSCWebService as $MSFT_xDSCWebService2ref
{
ResourceID = "[xDSCWebService]PSDSCComplianceServer";
 PhysicalPath = "C:\\inetpub\\wwwroot\\PSDSCComplianceServer";
 State = "Started";
 CertificateThumbPrint = "0B8D21D9A61EE3B5737CD7CF9ECC2E19C4661A7A";
 Ensure = "Present";
 SourceInfo = "C:\\Program Files\\WindowsPowerShell\\DSC\\NewPullServer\\NewPullServer.ps1::31::9::xDscWebService";
 EndpointName = "PSDSCComplianceServer";
 IsComplianceServer = True;
 ModuleName = "xPSDesiredStateConfiguration";
 Port = 9080;
 ModuleVersion = "3.0.2.0";

DependsOn = {

    "[WindowsFeature]DSCServiceFeature",

     "[xDSCWebService]PSDSCPullServer"};


};
instance of OMI_ConfigurationDocument
{
 Version="1.0.0";
 Author="andreas.storlien";
 GenerationDate="10/29/2014 14:01:36";
 GenerationHost="ANDREAS";
};
